SELECT MANAGER.NAME 
FROM EMPLOYEE MANAGER INNER JOIN EMPLOYEE EMP 
ON MANAGER.ID = EMP.CHIEF_ID
WHERE MANAGER.SALARY > (
						SELECT AVG(SALARY)*2 
						FROM EMPLOYEE 
						WHERE 
							EMP.CHIEF_ID = MANAGER.ID)
GROUP BY MANAGER.NAME, MANAGER.ID, MANAGER.ID